
- name: Create sftp group
  group:
    name: "{{ sftp_group_name }}"
    state: present

- name: Create sftp user
  user:
    name: "{{ item.name }}"
    group: "{{ sftp_group_name }}"
    shell: /usr/sbin/nologin
    state: present
  loop: "{{ sftp_users }}"

- name: Add authorized key for sftp user
  authorized_key: 
    user: "{{ item.name }}"
    state: present
    key: "{{ item.key }}"
  loop: "{{ sftp_users }}"

- name: Create directory
  file:
    path: "/home/{{ item.name }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop: "{{ sftp_users }}"
    
- name: Create sftp directory
  file:
    path: "/home/{{ item.name }}/sftp"
    state: directory
    owner: "{{ item.name }}"
    group: "{{ sftp_group_name }}"
    mode: '0750'
  loop: "{{ sftp_users }}"

- name: Ensure SSH listens on port 22 and 2222
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?Port 22$'
    line: "Port 22\nPort 2222"
    insertbefore: BOF
    validate: '/usr/sbin/sshd -t -f %s'
  notify:
    - Reload systemd
    - Restart ssh socket
    - Restart ssh

- name: Configure sshd for sftp
  blockinfile:
    path: /etc/ssh/sshd_config
    validate: /usr/sbin/sshd -t -f %s
    block: |
      Match LocalPort 2222
        ForceCommand internal-sftp
        AllowTcpForwarding no
        X11Forwarding no
        PasswordAuthentication no

      Match Group {{ sftp_group_name }}
        ChrootDirectory /home/%u
        ForceCommand internal-sftp
        AllowTcpForwarding no
        X11Forwarding no
        PasswordAuthentication no
  notify: Restart ssh