$ANSIBLE_VAULT;1.1;AES256
65313730346661336161656563303066616337613938363065613563636431653965383961626331
3265613838323062373161633465323033633766323432610a363636353230633865613736386431
34623162663761623463303135636231363530323634333066366239373531313936356164333466
3532613065646330610a393065363736306438353765316439653639326430333730356564356564
38356538313731633936663165313034633133373334643066653536663730633666616435646631
64663862366563643330623437393033616661353235356633343232646436383933633037343866
36326164393962366433353765323230323565653666613830383466326631346363636230396366
37333866303534376463366530613435383233356134353036333439656161623762363862656366
65613263396532653630366266646361303462623231636230386563613334616233353766666437
39323437666430616132336461353365366138383463353835666436316530336663336232383635
64343336646230613431313434316461363134636237393936336166653039353837366534363831
31626161316539653133333937616430353839636366376264626135373631316238366164373930
39346562313332663239633632346365363832643962663536666466663430333664366537346163
35303264633934393161626565613336666130343064353463393563323432306137656235303034
35316362383864316530353530363833326461653534336165313666356636373733313762653264
64333334313438326134343437363930336338623664353933353434623166393966383339663037
34383865346139306665313162306562343064333766643837616266633330623665
