- name : Apply common configuration to all servers
  hosts: all
  become: true
  roles:
    - common

- name: Setup jump host
  hosts: jump_host
  become: true
  roles:
    - jump_host

- name: Setup sftp server
  hosts: sftp
  become: true
  roles:
    - sftp_server
    - test

